
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username : sa
    password :
    driver-class-name: org.h2.Driver
