spring:
  jpa:
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:

        format_sql: true  # (3) SQL pretty print
  profiles:
    active: server # local / server
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  secret: ${JWT_SECRET_KEY} # JWT secret
  access-token-expiration-time: 30 # 30분 60 * 30
  refresh-token-expiration-time: 20000 # 2주 60 * 60 * 24 * 14
