spring:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Tjdwns3365!

  jpa:
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:

        format_sql: true  # (3) SQL pretty print
  profiles:
    include: local
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG








