spring:
  # H2 database
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    hikari:
      jdbc-url:jdbc:h2:mem:test;MODE=MYSQL
  # JPA
  jpa:
    hibernate:
      ddl-auto: create # create | create-drop | update | validate | none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb


# logging
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true # HTTP encoding charset
      charset: UTF-8 # HTTP encoding charset
jwt:
  secret: "c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK" # JWT secret
  access-token-expiration-time:  30 # 30분 60 * 30
  refresh-token-expiration-time: 20000 # 2주 60 * 60 * 24 * 14

mail:
  address:
    admin: admin@localhost # 관리자 이메일
