spring:
  # H2 database
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  # JPA
  jpa:
    hibernate:
      ddl-auto: create # create | create-drop | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# logging
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true # HTTP encoding charset
      charset: UTF-8 # HTTP encoding charset
