spring:
  jpa:
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:

        format_sql: true  # (3) SQL pretty print
  profiles:
    active: local
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
