spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1q2w3e4r!
    url: jdbc:mysql://seb40-pre-017.c0vpeyinlsgj.ap-northeast-2.rds.amazonaws.com:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: update # create | create-drop | update | validate | none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        
server:
  servlet:
    encoding:
      force-response: true # HTTP encoding charset
      charset: UTF-8 # HTTP encoding charset
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK # JWT secret
  access-token-expiration-time: 30 # 30분 60 * 30
  refresh-token-expiration-time: 20000 # 2주 60 * 60 * 24 * 14

mail:
  address:
    admin: admin@localhost # 관리자 이메일

cloud:
  aws:
    s3:
      bucket: pre-project-bucket-seb40-017
    credentials:
      access-key: AKIA4BVPCVUBFXOKFZ5W
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
